---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-multitool
  template:
    metadata:
      labels:
        app: app-multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: busy-volume
            mountPath: "/busy"
      volumes:
        - name: busy-volume
          persistentVolumeClaim:
            claimName: nfs-pvc