all:
  hosts:
    masternod:
      ansible_host: 172.16.0.30
      ip: 172.16.0.30
      access_ip: 172.16.0.30
      ansible_user: yc-user
    workernod1:
      ansible_host: 172.16.0.4
      ip: 172.16.0.4
      access_ip: 172.16.0.4
      ansible_user: yc-user
    workernod2:
      ansible_host: 172.16.0.6
      ip: 172.16.0.6
      access_ip: 172.16.0.6
      ansible_user: yc-user
    workernod3:
      ansible_host: 172.16.0.13
      ip: 172.16.0.13
      access_ip: 172.16.0.13
      ansible_user: yc-user
    workernod4:
      ansible_host: 172.16.0.35
      ip: 172.16.0.35
      access_ip: 172.16.0.35
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        masternod:
    kube_node:
      hosts:
        workernod1:
        workernod2:
        workernod3:
        workernod4:
    etcd:
      hosts:
        masternod:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}