apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app-deploy
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: multitool
      port: 9002
      targetPort: 8080
